//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/Settings/PlayerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Settings/PlayerAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerAction"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""64d4fdc6-7b32-4be9-90f6-1df4b7dcbc68"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""f8f265d0-d878-46d5-a05b-0bcd6f2217a1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""9543444d-d754-4302-b14e-db31bc79eab7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveForward"",
                    ""type"": ""Button"",
                    ""id"": ""f2f7c4b3-b0a2-494b-ab07-d552e47e6773"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveBackward"",
                    ""type"": ""Button"",
                    ""id"": ""417f59e8-6a05-4382-bbe6-ad607096cb9c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""34148441-bfd1-4cc6-9349-fe595a8841a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveToRight"",
                    ""type"": ""Button"",
                    ""id"": ""db364c65-6de5-45d8-b846-0ef1c1dd3074"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dc7c31c7-adb6-4894-bb72-fd418978b1fc"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""adb03634-1d67-4f13-93a5-7b60ab311232"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61d620b5-cd3d-4aa7-80ce-faf47bacd19e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f6566e0-ed9b-4e3c-b83f-c077f0972607"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3559e02-03be-46de-9198-7bba69b6ef76"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9a6e454-ec33-4333-94dc-a23ed1143089"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBackward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""325babb9-d0bb-4654-8ba0-eedfb081725e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87b9778a-9b71-48c5-b775-c8d432cd03c3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c114dfaa-7026-4faf-b610-23d3cad961a7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b3c81a0-bbcd-4164-aea1-5735ac493103"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ec62c3bc-500b-48e0-99ac-28cf5d472e29"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9be8fa76-1ba2-4f6b-ac6d-19a4bd6c9e70"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerMoves"",
            ""id"": ""91e805a1-a4ee-4ee7-9479-df584b45414b"",
            ""actions"": [
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""acb23ba6-f5eb-48c5-91a8-a4cbc51b081e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""74d06ce1-0104-454a-9d1d-d935c9949ef8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMode"",
                    ""type"": ""Button"",
                    ""id"": ""e2abff94-0dc7-4906-bbe4-daf6c9e6e707"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4213090f-de68-4df3-9142-373e94d61e46"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeHidePhone"",
                    ""type"": ""Button"",
                    ""id"": ""79b9df62-502b-4abe-88d5-dee1765f7df7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EditMode"",
                    ""type"": ""Button"",
                    ""id"": ""297944be-348f-469b-9af3-c2bc6f36f2d4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowObjectLeft"",
                    ""type"": ""Button"",
                    ""id"": ""32931795-6a6f-4db3-af1f-d2e9eca6964b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowObjectRight"",
                    ""type"": ""Button"",
                    ""id"": ""e61459b1-54a2-45ed-b205-970561e5268e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeUseObjectLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6b296b46-0d3b-4320-96f2-d1bd80767f82"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeUseObjectRight"",
                    ""type"": ""Button"",
                    ""id"": ""55e81940-7bd4-4291-807d-e10e13d46ff3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConsumeItem1"",
                    ""type"": ""Button"",
                    ""id"": ""fe6fc8f8-1a92-4d59-8d6c-681e830137e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConsumeItem2"",
                    ""type"": ""Button"",
                    ""id"": ""e60c3f2e-3ea8-4955-b003-2ba87b0cdaac"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConsumeItem3"",
                    ""type"": ""Button"",
                    ""id"": ""edbe64b8-1712-4286-a4b7-d4f2847e68e4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PhoneLight"",
                    ""type"": ""Button"",
                    ""id"": ""df8ad077-142f-4c37-bb8e-581a75fedf77"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bfac5a40-bf63-4df7-a944-88941cc87c15"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""EditMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09746c65-d54f-4fc1-b38d-044a3cb32faf"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""EditMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7127506c-8f7e-410a-8ce3-5268102ca57a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ConsumeItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0097e89-eecf-4f5d-9828-35c7cdf05597"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ConsumeItem1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0aee1901-652e-4969-8b47-9f0d7ff0a655"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ConsumeItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbeac3c4-43b7-4093-ae25-617b491d87eb"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ConsumeItem2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""760ee30a-1d40-48f4-b665-f810bf9088f1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ConsumeItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6f9a28f-890b-406e-b403-612a826fca4e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""ConsumeItem3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f6336a6-90fb-4144-b6ac-904e16240fd7"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""TakeHidePhone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6ea6e19-3e25-46ea-a99d-3618f6154f32"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""TakeHidePhone"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea1758e9-670e-45c2-9bff-9474e8b8a3d2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""CameraMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""23046b4b-1d69-4e31-ad54-69c6d8e24a4e"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""CameraMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1505da14-ce79-49ef-84f1-a3e3ef496a1f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3762c0d5-3070-4c1b-a77d-81f3947da4a6"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4734886f-8c38-43c1-9924-fe8b5a95e541"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea176ac0-d054-43ca-9022-96a544b28bf3"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""322f18ec-316f-47dd-8150-b606760bbdb3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""PhoneLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""87051ba9-9663-4ae3-ae21-eada78920627"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""PhoneLight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""afc38823-e66c-400a-9e36-8fc3bba5ca0f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeUseObjectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3150366a-c51d-4503-b357-8c2f70582a61"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeUseObjectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0784c43b-1705-4aad-9e18-74b2211a2545"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeUseObjectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4eed66d0-875c-44e9-b09f-25d4f44075a5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeUseObjectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5067496-10f5-46e2-89b3-4e0180c0a174"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowObjectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41d3f490-a139-48c5-8518-f735ffefc552"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowObjectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6052a82e-4981-4d91-82ea-de3c9457b219"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowObjectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a950b3a1-43cb-4400-8d58-b561842109f1"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowObjectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed30de3a-fe51-468a-b685-c8f8677eb6b4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4385162b-7345-4c7c-84b3-a2c74b59e477"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CameraMoves"",
            ""id"": ""3227c441-a5a1-4635-8efb-74e5128d3a40"",
            ""actions"": [
                {
                    ""name"": ""PreviousCamera"",
                    ""type"": ""Button"",
                    ""id"": ""812dc282-bc43-40cd-bf48-efb3432e83f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextCamera"",
                    ""type"": ""Button"",
                    ""id"": ""afe4324a-1439-4dff-b431-4143ac3ec1d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3d6af3fe-0925-4d7f-aaef-cf646874cc5a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c312842-f227-47e3-a02f-9a39b71ffc13"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PreviousCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3997697-be56-4663-9ba5-da385073754d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd343702-342b-4294-8adc-8e567c2627d4"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Global
        m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
        m_Global_Pause = m_Global.FindAction("Pause", throwIfNotFound: true);
        m_Global_Look = m_Global.FindAction("Look", throwIfNotFound: true);
        m_Global_MoveForward = m_Global.FindAction("MoveForward", throwIfNotFound: true);
        m_Global_MoveBackward = m_Global.FindAction("MoveBackward", throwIfNotFound: true);
        m_Global_MoveToLeft = m_Global.FindAction("MoveToLeft", throwIfNotFound: true);
        m_Global_MoveToRight = m_Global.FindAction("MoveToRight", throwIfNotFound: true);
        // PlayerMoves
        m_PlayerMoves = asset.FindActionMap("PlayerMoves", throwIfNotFound: true);
        m_PlayerMoves_Sprint = m_PlayerMoves.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerMoves_Crouch = m_PlayerMoves.FindAction("Crouch", throwIfNotFound: true);
        m_PlayerMoves_CameraMode = m_PlayerMoves.FindAction("CameraMode", throwIfNotFound: true);
        m_PlayerMoves_Interact = m_PlayerMoves.FindAction("Interact", throwIfNotFound: true);
        m_PlayerMoves_TakeHidePhone = m_PlayerMoves.FindAction("TakeHidePhone", throwIfNotFound: true);
        m_PlayerMoves_EditMode = m_PlayerMoves.FindAction("EditMode", throwIfNotFound: true);
        m_PlayerMoves_ThrowObjectLeft = m_PlayerMoves.FindAction("ThrowObjectLeft", throwIfNotFound: true);
        m_PlayerMoves_ThrowObjectRight = m_PlayerMoves.FindAction("ThrowObjectRight", throwIfNotFound: true);
        m_PlayerMoves_TakeUseObjectLeft = m_PlayerMoves.FindAction("TakeUseObjectLeft", throwIfNotFound: true);
        m_PlayerMoves_TakeUseObjectRight = m_PlayerMoves.FindAction("TakeUseObjectRight", throwIfNotFound: true);
        m_PlayerMoves_ConsumeItem1 = m_PlayerMoves.FindAction("ConsumeItem1", throwIfNotFound: true);
        m_PlayerMoves_ConsumeItem2 = m_PlayerMoves.FindAction("ConsumeItem2", throwIfNotFound: true);
        m_PlayerMoves_ConsumeItem3 = m_PlayerMoves.FindAction("ConsumeItem3", throwIfNotFound: true);
        m_PlayerMoves_PhoneLight = m_PlayerMoves.FindAction("PhoneLight", throwIfNotFound: true);
        // CameraMoves
        m_CameraMoves = asset.FindActionMap("CameraMoves", throwIfNotFound: true);
        m_CameraMoves_PreviousCamera = m_CameraMoves.FindAction("PreviousCamera", throwIfNotFound: true);
        m_CameraMoves_NextCamera = m_CameraMoves.FindAction("NextCamera", throwIfNotFound: true);
    }

    ~@PlayerAction()
    {
        UnityEngine.Debug.Assert(!m_Global.enabled, "This will cause a leak and performance issues, PlayerAction.Global.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PlayerMoves.enabled, "This will cause a leak and performance issues, PlayerAction.PlayerMoves.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CameraMoves.enabled, "This will cause a leak and performance issues, PlayerAction.CameraMoves.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Global
    private readonly InputActionMap m_Global;
    private List<IGlobalActions> m_GlobalActionsCallbackInterfaces = new List<IGlobalActions>();
    private readonly InputAction m_Global_Pause;
    private readonly InputAction m_Global_Look;
    private readonly InputAction m_Global_MoveForward;
    private readonly InputAction m_Global_MoveBackward;
    private readonly InputAction m_Global_MoveToLeft;
    private readonly InputAction m_Global_MoveToRight;
    /// <summary>
    /// Provides access to input actions defined in input action map "Global".
    /// </summary>
    public struct GlobalActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GlobalActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Global/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_Global_Pause;
        /// <summary>
        /// Provides access to the underlying input action "Global/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_Global_Look;
        /// <summary>
        /// Provides access to the underlying input action "Global/MoveForward".
        /// </summary>
        public InputAction @MoveForward => m_Wrapper.m_Global_MoveForward;
        /// <summary>
        /// Provides access to the underlying input action "Global/MoveBackward".
        /// </summary>
        public InputAction @MoveBackward => m_Wrapper.m_Global_MoveBackward;
        /// <summary>
        /// Provides access to the underlying input action "Global/MoveToLeft".
        /// </summary>
        public InputAction @MoveToLeft => m_Wrapper.m_Global_MoveToLeft;
        /// <summary>
        /// Provides access to the underlying input action "Global/MoveToRight".
        /// </summary>
        public InputAction @MoveToRight => m_Wrapper.m_Global_MoveToRight;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Global; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GlobalActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GlobalActions" />
        public void AddCallbacks(IGlobalActions instance)
        {
            if (instance == null || m_Wrapper.m_GlobalActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GlobalActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @MoveForward.started += instance.OnMoveForward;
            @MoveForward.performed += instance.OnMoveForward;
            @MoveForward.canceled += instance.OnMoveForward;
            @MoveBackward.started += instance.OnMoveBackward;
            @MoveBackward.performed += instance.OnMoveBackward;
            @MoveBackward.canceled += instance.OnMoveBackward;
            @MoveToLeft.started += instance.OnMoveToLeft;
            @MoveToLeft.performed += instance.OnMoveToLeft;
            @MoveToLeft.canceled += instance.OnMoveToLeft;
            @MoveToRight.started += instance.OnMoveToRight;
            @MoveToRight.performed += instance.OnMoveToRight;
            @MoveToRight.canceled += instance.OnMoveToRight;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GlobalActions" />
        private void UnregisterCallbacks(IGlobalActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @MoveForward.started -= instance.OnMoveForward;
            @MoveForward.performed -= instance.OnMoveForward;
            @MoveForward.canceled -= instance.OnMoveForward;
            @MoveBackward.started -= instance.OnMoveBackward;
            @MoveBackward.performed -= instance.OnMoveBackward;
            @MoveBackward.canceled -= instance.OnMoveBackward;
            @MoveToLeft.started -= instance.OnMoveToLeft;
            @MoveToLeft.performed -= instance.OnMoveToLeft;
            @MoveToLeft.canceled -= instance.OnMoveToLeft;
            @MoveToRight.started -= instance.OnMoveToRight;
            @MoveToRight.performed -= instance.OnMoveToRight;
            @MoveToRight.canceled -= instance.OnMoveToRight;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />.
        /// </summary>
        /// <seealso cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />
        public void RemoveCallbacks(IGlobalActions instance)
        {
            if (m_Wrapper.m_GlobalActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GlobalActions.AddCallbacks(IGlobalActions)" />
        /// <seealso cref="GlobalActions.RemoveCallbacks(IGlobalActions)" />
        /// <seealso cref="GlobalActions.UnregisterCallbacks(IGlobalActions)" />
        public void SetCallbacks(IGlobalActions instance)
        {
            foreach (var item in m_Wrapper.m_GlobalActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GlobalActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GlobalActions" /> instance referencing this action map.
    /// </summary>
    public GlobalActions @Global => new GlobalActions(this);

    // PlayerMoves
    private readonly InputActionMap m_PlayerMoves;
    private List<IPlayerMovesActions> m_PlayerMovesActionsCallbackInterfaces = new List<IPlayerMovesActions>();
    private readonly InputAction m_PlayerMoves_Sprint;
    private readonly InputAction m_PlayerMoves_Crouch;
    private readonly InputAction m_PlayerMoves_CameraMode;
    private readonly InputAction m_PlayerMoves_Interact;
    private readonly InputAction m_PlayerMoves_TakeHidePhone;
    private readonly InputAction m_PlayerMoves_EditMode;
    private readonly InputAction m_PlayerMoves_ThrowObjectLeft;
    private readonly InputAction m_PlayerMoves_ThrowObjectRight;
    private readonly InputAction m_PlayerMoves_TakeUseObjectLeft;
    private readonly InputAction m_PlayerMoves_TakeUseObjectRight;
    private readonly InputAction m_PlayerMoves_ConsumeItem1;
    private readonly InputAction m_PlayerMoves_ConsumeItem2;
    private readonly InputAction m_PlayerMoves_ConsumeItem3;
    private readonly InputAction m_PlayerMoves_PhoneLight;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerMoves".
    /// </summary>
    public struct PlayerMovesActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerMovesActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/Sprint".
        /// </summary>
        public InputAction @Sprint => m_Wrapper.m_PlayerMoves_Sprint;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/Crouch".
        /// </summary>
        public InputAction @Crouch => m_Wrapper.m_PlayerMoves_Crouch;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/CameraMode".
        /// </summary>
        public InputAction @CameraMode => m_Wrapper.m_PlayerMoves_CameraMode;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/Interact".
        /// </summary>
        public InputAction @Interact => m_Wrapper.m_PlayerMoves_Interact;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/TakeHidePhone".
        /// </summary>
        public InputAction @TakeHidePhone => m_Wrapper.m_PlayerMoves_TakeHidePhone;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/EditMode".
        /// </summary>
        public InputAction @EditMode => m_Wrapper.m_PlayerMoves_EditMode;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/ThrowObjectLeft".
        /// </summary>
        public InputAction @ThrowObjectLeft => m_Wrapper.m_PlayerMoves_ThrowObjectLeft;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/ThrowObjectRight".
        /// </summary>
        public InputAction @ThrowObjectRight => m_Wrapper.m_PlayerMoves_ThrowObjectRight;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/TakeUseObjectLeft".
        /// </summary>
        public InputAction @TakeUseObjectLeft => m_Wrapper.m_PlayerMoves_TakeUseObjectLeft;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/TakeUseObjectRight".
        /// </summary>
        public InputAction @TakeUseObjectRight => m_Wrapper.m_PlayerMoves_TakeUseObjectRight;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/ConsumeItem1".
        /// </summary>
        public InputAction @ConsumeItem1 => m_Wrapper.m_PlayerMoves_ConsumeItem1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/ConsumeItem2".
        /// </summary>
        public InputAction @ConsumeItem2 => m_Wrapper.m_PlayerMoves_ConsumeItem2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/ConsumeItem3".
        /// </summary>
        public InputAction @ConsumeItem3 => m_Wrapper.m_PlayerMoves_ConsumeItem3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerMoves/PhoneLight".
        /// </summary>
        public InputAction @PhoneLight => m_Wrapper.m_PlayerMoves_PhoneLight;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerMoves; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerMovesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerMovesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerMovesActions" />
        public void AddCallbacks(IPlayerMovesActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMovesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMovesActionsCallbackInterfaces.Add(instance);
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @CameraMode.started += instance.OnCameraMode;
            @CameraMode.performed += instance.OnCameraMode;
            @CameraMode.canceled += instance.OnCameraMode;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @TakeHidePhone.started += instance.OnTakeHidePhone;
            @TakeHidePhone.performed += instance.OnTakeHidePhone;
            @TakeHidePhone.canceled += instance.OnTakeHidePhone;
            @EditMode.started += instance.OnEditMode;
            @EditMode.performed += instance.OnEditMode;
            @EditMode.canceled += instance.OnEditMode;
            @ThrowObjectLeft.started += instance.OnThrowObjectLeft;
            @ThrowObjectLeft.performed += instance.OnThrowObjectLeft;
            @ThrowObjectLeft.canceled += instance.OnThrowObjectLeft;
            @ThrowObjectRight.started += instance.OnThrowObjectRight;
            @ThrowObjectRight.performed += instance.OnThrowObjectRight;
            @ThrowObjectRight.canceled += instance.OnThrowObjectRight;
            @TakeUseObjectLeft.started += instance.OnTakeUseObjectLeft;
            @TakeUseObjectLeft.performed += instance.OnTakeUseObjectLeft;
            @TakeUseObjectLeft.canceled += instance.OnTakeUseObjectLeft;
            @TakeUseObjectRight.started += instance.OnTakeUseObjectRight;
            @TakeUseObjectRight.performed += instance.OnTakeUseObjectRight;
            @TakeUseObjectRight.canceled += instance.OnTakeUseObjectRight;
            @ConsumeItem1.started += instance.OnConsumeItem1;
            @ConsumeItem1.performed += instance.OnConsumeItem1;
            @ConsumeItem1.canceled += instance.OnConsumeItem1;
            @ConsumeItem2.started += instance.OnConsumeItem2;
            @ConsumeItem2.performed += instance.OnConsumeItem2;
            @ConsumeItem2.canceled += instance.OnConsumeItem2;
            @ConsumeItem3.started += instance.OnConsumeItem3;
            @ConsumeItem3.performed += instance.OnConsumeItem3;
            @ConsumeItem3.canceled += instance.OnConsumeItem3;
            @PhoneLight.started += instance.OnPhoneLight;
            @PhoneLight.performed += instance.OnPhoneLight;
            @PhoneLight.canceled += instance.OnPhoneLight;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerMovesActions" />
        private void UnregisterCallbacks(IPlayerMovesActions instance)
        {
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @CameraMode.started -= instance.OnCameraMode;
            @CameraMode.performed -= instance.OnCameraMode;
            @CameraMode.canceled -= instance.OnCameraMode;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @TakeHidePhone.started -= instance.OnTakeHidePhone;
            @TakeHidePhone.performed -= instance.OnTakeHidePhone;
            @TakeHidePhone.canceled -= instance.OnTakeHidePhone;
            @EditMode.started -= instance.OnEditMode;
            @EditMode.performed -= instance.OnEditMode;
            @EditMode.canceled -= instance.OnEditMode;
            @ThrowObjectLeft.started -= instance.OnThrowObjectLeft;
            @ThrowObjectLeft.performed -= instance.OnThrowObjectLeft;
            @ThrowObjectLeft.canceled -= instance.OnThrowObjectLeft;
            @ThrowObjectRight.started -= instance.OnThrowObjectRight;
            @ThrowObjectRight.performed -= instance.OnThrowObjectRight;
            @ThrowObjectRight.canceled -= instance.OnThrowObjectRight;
            @TakeUseObjectLeft.started -= instance.OnTakeUseObjectLeft;
            @TakeUseObjectLeft.performed -= instance.OnTakeUseObjectLeft;
            @TakeUseObjectLeft.canceled -= instance.OnTakeUseObjectLeft;
            @TakeUseObjectRight.started -= instance.OnTakeUseObjectRight;
            @TakeUseObjectRight.performed -= instance.OnTakeUseObjectRight;
            @TakeUseObjectRight.canceled -= instance.OnTakeUseObjectRight;
            @ConsumeItem1.started -= instance.OnConsumeItem1;
            @ConsumeItem1.performed -= instance.OnConsumeItem1;
            @ConsumeItem1.canceled -= instance.OnConsumeItem1;
            @ConsumeItem2.started -= instance.OnConsumeItem2;
            @ConsumeItem2.performed -= instance.OnConsumeItem2;
            @ConsumeItem2.canceled -= instance.OnConsumeItem2;
            @ConsumeItem3.started -= instance.OnConsumeItem3;
            @ConsumeItem3.performed -= instance.OnConsumeItem3;
            @ConsumeItem3.canceled -= instance.OnConsumeItem3;
            @PhoneLight.started -= instance.OnPhoneLight;
            @PhoneLight.performed -= instance.OnPhoneLight;
            @PhoneLight.canceled -= instance.OnPhoneLight;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerMovesActions.UnregisterCallbacks(IPlayerMovesActions)" />.
        /// </summary>
        /// <seealso cref="PlayerMovesActions.UnregisterCallbacks(IPlayerMovesActions)" />
        public void RemoveCallbacks(IPlayerMovesActions instance)
        {
            if (m_Wrapper.m_PlayerMovesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerMovesActions.AddCallbacks(IPlayerMovesActions)" />
        /// <seealso cref="PlayerMovesActions.RemoveCallbacks(IPlayerMovesActions)" />
        /// <seealso cref="PlayerMovesActions.UnregisterCallbacks(IPlayerMovesActions)" />
        public void SetCallbacks(IPlayerMovesActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMovesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMovesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerMovesActions" /> instance referencing this action map.
    /// </summary>
    public PlayerMovesActions @PlayerMoves => new PlayerMovesActions(this);

    // CameraMoves
    private readonly InputActionMap m_CameraMoves;
    private List<ICameraMovesActions> m_CameraMovesActionsCallbackInterfaces = new List<ICameraMovesActions>();
    private readonly InputAction m_CameraMoves_PreviousCamera;
    private readonly InputAction m_CameraMoves_NextCamera;
    /// <summary>
    /// Provides access to input actions defined in input action map "CameraMoves".
    /// </summary>
    public struct CameraMovesActions
    {
        private @PlayerAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CameraMovesActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CameraMoves/PreviousCamera".
        /// </summary>
        public InputAction @PreviousCamera => m_Wrapper.m_CameraMoves_PreviousCamera;
        /// <summary>
        /// Provides access to the underlying input action "CameraMoves/NextCamera".
        /// </summary>
        public InputAction @NextCamera => m_Wrapper.m_CameraMoves_NextCamera;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CameraMoves; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CameraMovesActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CameraMovesActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CameraMovesActions" />
        public void AddCallbacks(ICameraMovesActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraMovesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraMovesActionsCallbackInterfaces.Add(instance);
            @PreviousCamera.started += instance.OnPreviousCamera;
            @PreviousCamera.performed += instance.OnPreviousCamera;
            @PreviousCamera.canceled += instance.OnPreviousCamera;
            @NextCamera.started += instance.OnNextCamera;
            @NextCamera.performed += instance.OnNextCamera;
            @NextCamera.canceled += instance.OnNextCamera;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CameraMovesActions" />
        private void UnregisterCallbacks(ICameraMovesActions instance)
        {
            @PreviousCamera.started -= instance.OnPreviousCamera;
            @PreviousCamera.performed -= instance.OnPreviousCamera;
            @PreviousCamera.canceled -= instance.OnPreviousCamera;
            @NextCamera.started -= instance.OnNextCamera;
            @NextCamera.performed -= instance.OnNextCamera;
            @NextCamera.canceled -= instance.OnNextCamera;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CameraMovesActions.UnregisterCallbacks(ICameraMovesActions)" />.
        /// </summary>
        /// <seealso cref="CameraMovesActions.UnregisterCallbacks(ICameraMovesActions)" />
        public void RemoveCallbacks(ICameraMovesActions instance)
        {
            if (m_Wrapper.m_CameraMovesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CameraMovesActions.AddCallbacks(ICameraMovesActions)" />
        /// <seealso cref="CameraMovesActions.RemoveCallbacks(ICameraMovesActions)" />
        /// <seealso cref="CameraMovesActions.UnregisterCallbacks(ICameraMovesActions)" />
        public void SetCallbacks(ICameraMovesActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraMovesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraMovesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CameraMovesActions" /> instance referencing this action map.
    /// </summary>
    public CameraMovesActions @CameraMoves => new CameraMovesActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Global" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GlobalActions.AddCallbacks(IGlobalActions)" />
    /// <seealso cref="GlobalActions.RemoveCallbacks(IGlobalActions)" />
    public interface IGlobalActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveForward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveForward(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveBackward" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveBackward(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MoveToRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveToRight(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerMoves" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerMovesActions.AddCallbacks(IPlayerMovesActions)" />
    /// <seealso cref="PlayerMovesActions.RemoveCallbacks(IPlayerMovesActions)" />
    public interface IPlayerMovesActions
    {
        /// <summary>
        /// Method invoked when associated input action "Sprint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSprint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Crouch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCrouch(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CameraMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCameraMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteract(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TakeHidePhone" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTakeHidePhone(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "EditMode" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnEditMode(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrowObjectLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrowObjectLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ThrowObjectRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrowObjectRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TakeUseObjectLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTakeUseObjectLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TakeUseObjectRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTakeUseObjectRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ConsumeItem1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConsumeItem1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ConsumeItem2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConsumeItem2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ConsumeItem3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnConsumeItem3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PhoneLight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPhoneLight(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CameraMoves" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CameraMovesActions.AddCallbacks(ICameraMovesActions)" />
    /// <seealso cref="CameraMovesActions.RemoveCallbacks(ICameraMovesActions)" />
    public interface ICameraMovesActions
    {
        /// <summary>
        /// Method invoked when associated input action "PreviousCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPreviousCamera(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextCamera" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextCamera(InputAction.CallbackContext context);
    }
}
