name: Discord Push Notification

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "<@&1493962854389387294> 🚀 Nouveau push sur le projet Unity !\nAuteur: '${{ github.actor }}'\nBranche: '${{ github.ref_name }}'\nCommit: '${{ github.event.head_commit.message }}'"
          }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}