name: Discord Push Notification

on:
  push:

jobs:
  notify:

    steps:
      - name: Notify Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "🔔 Nouveau push sur **${{ github.repository }}**\n👤 Auteur : **${{ github.actor }}**\n🌿 Branche : **${{ github.ref_name }}**\n📝 Commit : **${{ github.event.head_commit.message }}**"
          }' \
          "$WEBHOOK"
